# Generated by Django 2.1.7 on 2019-03-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, null=True)),
                ('count', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('algorithm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('text', models.TextField()),
                ('status', models.IntegerField()),
                ('file_name', models.CharField(max_length=300, null=True)),
                ('path', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('alias', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=20)),
                ('documents', models.ManyToManyField(to='discover.Document')),
            ],
        ),
        migrations.AddField(
            model_name='cluster',
            name='entities',
            field=models.ManyToManyField(to='discover.Entity'),
        ),
    ]
